export const AppConstants = {
    UDP_MESSAGE_RECEIVED: 'UDP_MESSAGE_RECEIVED',
    TCP_MESSAGE_RECEIVED: 'TCP_MESSAGE_RECEIVED',
    VIDEO_DATA_RECEIVED: 'VIDEO_DATA_RECEIVED',
    MAX_TTL: 20000,
};

